name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env: 
          GATSBY_USER_ID: ${{ secrets.GATSBY_USER_ID }}
          GATSBY_SERVICE_ID: ${{ secrets.GATSBY_SERVICE_ID }}
        with:
          access-token: ${{ secrets.farmer_startup }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
        